name: Run FTMO Signals Bot

on:
  schedule:
    # 03:00 & 11:00 UTC (≈ 06:00 & 14:00 Asia/Jerusalem בקיץ)
    - cron: "0 3,11 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          TOKEN_FTMO: ${{ secrets.TOKEN_FTMO }}
          CHAT_ID_FTMO: ${{ secrets.CHAT_ID_FTMO }}
          ACCOUNT_SIZE: ${{ secrets.ACCOUNT_SIZE }}
          RISK_PER_TRADE_PERCENT: ${{ secrets.RISK_PER_TRADE_PERCENT }}
        run: |
          python bot.py
